"""wayback backfill: snapshot captured_at/origin/quality, change_event, asset_alias

Revision ID: 02d7a88188d4
Revises: 9f5de3fc7bf0
Create Date: 2026-06-12 08:34:14.240605
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '02d7a88188d4'
down_revision: str | None = '9f5de3fc7bf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_alias',
    sa.Column('alias_id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('alias', name='uq_asset_alias')
    )
    op.create_table('change_event',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('from_phase', sa.String(length=32), nullable=True),
    sa.Column('to_phase', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('last_phase', sa.String(length=32), nullable=True),
    sa.Column('exit_class', sa.String(length=32), nullable=True),
    sa.Column('partner', sa.Text(), nullable=True),
    sa.Column('eff_min', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eff_max', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_snapshot_id', sa.String(length=26), nullable=True),
    sa.Column('to_snapshot_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_change_event_company', 'change_event', ['company_id', 'event_type'], unique=False)
    op.add_column('snapshot', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    # server_default backfills existing rows (all prior snapshots are live scrapes); NOT NULL holds.
    op.add_column('snapshot', sa.Column('origin', sa.String(length=16), nullable=False,
                                        server_default='live'))
    op.add_column('snapshot', sa.Column('extraction_quality_score', sa.Numeric(), nullable=True))
    # backfill captured_at = fetched_at for existing live snapshots so the temporal anchor is set.
    op.execute("UPDATE snapshot SET captured_at = fetched_at WHERE captured_at IS NULL")
    op.create_index('ix_snapshot_source_captured', 'snapshot', ['source_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_source_captured', table_name='snapshot')
    op.drop_column('snapshot', 'extraction_quality_score')
    op.drop_column('snapshot', 'origin')
    op.drop_column('snapshot', 'captured_at')
    op.drop_index('ix_change_event_company', table_name='change_event')
    op.drop_table('change_event')
    op.drop_table('asset_alias')
    # ### end Alembic commands ###
