"""add enrichment provenance (asset.modality_source, asset_target.source)

Revision ID: 25dbd5dfee09
Revises: be165f264480
Create Date: 2026-06-11 21:04:26.928817
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25dbd5dfee09'
down_revision: str | None = 'be165f264480'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('modality_source', sa.String(length=16), nullable=False, server_default='disclosed'))
    op.add_column('asset_target', sa.Column('source', sa.String(length=16), nullable=False, server_default='disclosed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_target', 'source')
    op.drop_column('asset', 'modality_source')
    # ### end Alembic commands ###
