"""schema v1

Revision ID: 6ea3b1b88744
Revises: 
Create Date: 2026-06-10 11:18:49.248608
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = '6ea3b1b88744'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('parent_company_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('market_cap_usd', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('indication',
    sa.Column('indication_id', sa.String(length=26), nullable=False),
    sa.Column('preferred_label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('indication_id')
    )
    op.create_table('modality_vocab',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ontology_closure',
    sa.Column('ancestor_curie', sa.String(length=64), nullable=False),
    sa.Column('descendant_curie', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ancestor_curie', 'descendant_curie')
    )
    op.create_table('ontology_edge',
    sa.Column('parent_curie', sa.String(length=64), nullable=False),
    sa.Column('child_curie', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('parent_curie', 'child_curie')
    )
    op.create_table('ontology_term',
    sa.Column('curie', sa.String(length=64), nullable=False),
    sa.Column('ontology', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('obsolete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('curie')
    )
    op.create_table('phase_vocab',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('review_queue',
    sa.Column('item_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('entity_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('target',
    sa.Column('target_id', sa.String(length=26), nullable=False),
    sa.Column('hgnc_symbol', sa.String(length=64), nullable=True),
    sa.Column('uniprot_id', sa.String(length=32), nullable=True),
    sa.Column('ensembl_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('vocab_mapping',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('vocab', sa.String(length=32), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_mapping_lookup', 'vocab_mapping', ['vocab', sa.literal_column('lower(verbatim)')], unique=True)
    op.create_table('asset',
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.Column('preferred_name', sa.Text(), nullable=False),
    sa.Column('modality_code', sa.String(length=48), nullable=True),
    sa.Column('modality_verbatim', sa.Text(), nullable=True),
    sa.Column('originator_company_id', sa.String(length=26), nullable=True),
    sa.Column('chembl_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modality_code'], ['modality_vocab.code'], ),
    sa.ForeignKeyConstraint(['originator_company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('company_source',
    sa.Column('source_id', sa.String(length=26), nullable=False),
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('render_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('company_id', 'url', name='uq_company_source_url')
    )
    op.create_table('indication_mapping',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('indication_id', sa.String(length=26), nullable=False),
    sa.Column('ontology', sa.String(length=16), nullable=False),
    sa.Column('curie', sa.String(length=64), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.indication_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_run',
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('company_id', sa.String(length=26), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('program',
    sa.Column('program_id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.Column('indication_id', sa.String(length=26), nullable=False),
    sa.Column('company_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['indication_id'], ['indication.indication_id'], ),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('asset_id', 'indication_id', 'company_id', name='uq_program')
    )
    op.create_table('snapshot',
    sa.Column('snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('source_id', sa.String(length=26), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('html_key', sa.Text(), nullable=True),
    sa.Column('screenshot_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('render_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unchanged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['company_source.source_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index('ix_snapshot_source_fetched', 'snapshot', ['source_id', 'fetched_at'], unique=False)
    op.create_table('extraction',
    sa.Column('extraction_id', sa.String(length=26), nullable=False),
    sa.Column('snapshot_id', sa.String(length=26), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_table('program_embedding',
    sa.Column('program_id', sa.String(length=26), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('program_version',
    sa.Column('version_id', sa.String(length=26), nullable=False),
    sa.Column('program_id', sa.String(length=26), nullable=False),
    sa.Column('phase_code', sa.String(length=32), nullable=True),
    sa.Column('phase_verbatim', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('indication_verbatim', sa.Text(), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_snapshot_id', sa.String(length=26), nullable=True),
    sa.Column('last_seen_snapshot_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.ForeignKeyConstraint(['last_seen_snapshot_id'], ['snapshot.snapshot_id'], ),
    sa.ForeignKeyConstraint(['phase_code'], ['phase_vocab.code'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('uq_program_version_current', 'program_version', ['program_id'], unique=True, postgresql_where='valid_to IS NULL')
    op.create_table('asset_synonym',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.Column('synonym', sa.Text(), nullable=False),
    sa.Column('synonym_type', sa.String(length=32), nullable=False),
    sa.Column('source_extraction_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['source_extraction_id'], ['extraction.extraction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_synonym_lower', 'asset_synonym', ['asset_id', sa.literal_column('lower(synonym)')], unique=True)
    op.create_index('ix_asset_synonym_trgm', 'asset_synonym', ['synonym'], unique=False,
                    postgresql_using='gin', postgresql_ops={'synonym': 'gin_trgm_ops'})
    op.create_table('asset_target',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('asset_id', sa.String(length=26), nullable=False),
    sa.Column('target_id', sa.String(length=26), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('source_extraction_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['source_extraction_id'], ['extraction.extraction_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.target_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'target_id', name='uq_asset_target')
    )
    op.create_table('partnership',
    sa.Column('partnership_id', sa.String(length=26), nullable=False),
    sa.Column('program_id', sa.String(length=26), nullable=True),
    sa.Column('asset_id', sa.String(length=26), nullable=True),
    sa.Column('partner_company_id', sa.String(length=26), nullable=True),
    sa.Column('partner_name_verbatim', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('deal_type', sa.String(length=64), nullable=True),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('source_extraction_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['partner_company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.ForeignKeyConstraint(['source_extraction_id'], ['extraction.extraction_id'], ),
    sa.PrimaryKeyConstraint('partnership_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnership')
    op.drop_table('asset_target')
    op.drop_index('ix_asset_synonym_trgm', table_name='asset_synonym')
    op.drop_index('ix_asset_synonym_lower', table_name='asset_synonym')
    op.drop_table('asset_synonym')
    op.drop_index('uq_program_version_current', table_name='program_version', postgresql_where='valid_to IS NULL')
    op.drop_table('program_version')
    op.drop_table('program_embedding')
    op.drop_table('extraction')
    op.drop_index('ix_snapshot_source_fetched', table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_table('program')
    op.drop_table('job_run')
    op.drop_table('indication_mapping')
    op.drop_table('company_source')
    op.drop_table('asset')
    op.drop_index('ix_vocab_mapping_lookup', table_name='vocab_mapping')
    op.drop_table('vocab_mapping')
    op.drop_table('target')
    op.drop_table('review_queue')
    op.drop_table('phase_vocab')
    op.drop_table('ontology_term')
    op.drop_table('ontology_edge')
    op.drop_table('ontology_closure')
    op.drop_table('modality_vocab')
    op.drop_table('indication')
    op.drop_table('company')
    # ### end Alembic commands ###
