"""add asset.mechanism_verbatim (disclosed MoA)

Revision ID: 9f5de3fc7bf0
Revises: 25dbd5dfee09
Create Date: 2026-06-11 21:23:53.311464
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9f5de3fc7bf0'
down_revision: str | None = '25dbd5dfee09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('mechanism_verbatim', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'mechanism_verbatim')
    # ### end Alembic commands ###
