"""add indication_mapping.therapeutic_area

Revision ID: be165f264480
Revises: 09b9ab596a73
Create Date: 2026-06-11 09:26:29.725566
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be165f264480'
down_revision: str | None = '09b9ab596a73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indication_mapping', sa.Column('therapeutic_area', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indication_mapping', 'therapeutic_area')
    # ### end Alembic commands ###
